const ui = {
  FETCH_UI_CONTENT: 'FETCH_UI_CONTENT',
  STORE_UI_CONTENT: 'STORE_UI_CONTENT',
  IS_LOADING: 'IS_LOADING',
  SET_FILTER: 'SET_FILTER',
  CLEAR_FILTERS: 'CLEAR_FILTERS'
};

export { ui };
